version: '3'

services:
  workspace:
    build:
      context: ..
      dockerfile: python_uv_slim\Dockerfile
    environment:
      PYTHONPATH: /workspace
    volumes:
      - ../..:/workspace
    command: sleep infinity
